\begin{align}\label{eq:7}
    I(\omega_t, \omega_\tau) \propto
    & \int \dots \int^{\infty}_{-\infty} d \epsilon_{xx} d \epsilon_{yy} d \epsilon_{zz} d \epsilon_{yz} d \epsilon_{xy} d \epsilon_{zx} \\ 
    & \frac{1}{ \left( \sigma \sqrt{2 \pi} \right)^6 } exp \left[ \frac{-\epsilon_{xx}^2 -\epsilon_{yy}^2 -\epsilon_{zz}^2 -\epsilon_{yz}^2 -\epsilon_{xy}^2 -\epsilon_{zx}^2}{2 \sigma^2} \right] \\ 
    & \rho (\omega_t, \omega_{\tau}, \epsilon_{xx}, \epsilon_{yy}, \epsilon_{zz}, \epsilon_{yz}, \epsilon_{xy}, \epsilon_{zx})
\end{align}

\begin{equation}\label{eq:4}
    \rho (\omega_t, \omega_{\tau}, \epsilon_{xx}, \epsilon_{yy}, \epsilon_{zz}, \epsilon_{yz}, \epsilon_{xy}, \epsilon_{zx}) = - \left( \frac{1}{\omega_t-[\Delta_{ZPL} \pm \Delta_{gs} \pm \Delta_{es} - i \gamma_{10}]} \right ) \left (\frac{1}{\omega_{\tau}+[\Delta_{ZPL} \pm \Delta_{gs} \pm \Delta_{es} + i \gamma_{10}]} \right)
\end{equation}


\begin{equation}\label{eq:1}
    \Delta_{ZPL}(\epsilon_{xx}, \epsilon_{yy}, \epsilon_{zz}) = \Delta_{ZPL,0} + (t_{\parallel,es} - t_{\parallel,gs})\epsilon_{zz} + (t_{\perp,es} - t_{\perp,gs})(\epsilon_{xx} + \epsilon_{yy})
\end{equation}


\begin{equation}\label{eq:2}
    \Delta_{gs}(\epsilon_{xx}, \epsilon_{yy}, \epsilon_{yz}, \epsilon_{xy}, \epsilon_{zx}) = \sqrt{\lambda_{SO,gs}^2 + 4[d_{gs}(\epsilon_{xx} - \epsilon_{yy}) + f_{gs} \epsilon_{yz}]^2 + 4[-2d_{gs} \epsilon_{xy} + f_{gs} \epsilon_{zx}]^2}
\end{equation}

\begin{equation}\label{eq:3}
    \Delta_{es}(\epsilon_{xx}, \epsilon_{yy}, \epsilon_{yz}, \epsilon_{xy}, \epsilon_{zx}) = \sqrt{\lambda_{SO,es}^2 + 4[d_{es}(\epsilon_{xx} - \epsilon_{yy}) + f_{es} \epsilon_{yz}]^2 + 4[-2d_{es} \epsilon_{xy} + f_{es} \epsilon_{zx}]^2}
\end{equation}

# Monte Carlo Integration

\begin{align}\label{eq:8}
\int_{\bar{x_a}}^{\bar{x_b}} f(\bar{x}) \, d\bar{x} 
& = \left \langle \frac{f(\bar{x})}{p(\bar{x})} \right \rangle_p \int_{\bar{x_a}}^{\bar{x_b}}p(\bar{x}) \, d\bar{x} \\
& \approx \frac{1}{N} \sum_i^N \frac{f(\bar{x}_i)}{p(\bar{x}_i)} \int_{\bar{x_a}}^{\bar{x_b}} p(\bar{x}) \, d\bar{x}
\end{align}

\begin{equation}\label{eq:}
\bar{x} \in \{ x_1, x_2, x_3, \dots\}
\end{equation}


## random numbers drawn from $p(x)$

\begin{equation}\label{eq:9}
f(\epsilon_{xx}, \epsilon_{yy}, \epsilon_{zz}, \epsilon_{yz}, \epsilon_{xy}, \epsilon_{zx}) = \frac{1}{ \left( \sigma \sqrt{2 \pi} \right)^6 } exp \left[ \frac{-\epsilon_{xx}^2 -\epsilon_{yy}^2 -\epsilon_{zz}^2 -\epsilon_{yz}^2 -\epsilon_{xy}^2 -\epsilon_{zx}^2}{2 \sigma^2} \right] \rho (\omega_t, \omega_{\tau}, \epsilon_{xx}, \epsilon_{yy}, \epsilon_{zz}, \epsilon_{yz}, \epsilon_{xy}, \epsilon_{zx})
\end{equation}


\begin{equation}\label{eq:10}
p(\epsilon_{xx}, \epsilon_{yy}, \epsilon_{zz}, \epsilon_{yz}, \epsilon_{xy}, \epsilon_{zx}) = \frac{1}{ \left( \sigma \sqrt{2 \pi} \right)^6 } exp \left[ \frac{-\epsilon_{xx}^2 -\epsilon_{yy}^2 -\epsilon_{zz}^2 -\epsilon_{yz}^2 -\epsilon_{xy}^2 -\epsilon_{zx}^2}{2 \sigma^2} \right]
\end{equation}


\begin{equation}\label{eq:12}
\int \dots \int^{\infty}_{-\infty} d \epsilon_{xx} d \epsilon_{yy} d \epsilon_{zz} d \epsilon_{yz} d \epsilon_{xy} d \epsilon_{zx} \, p(\epsilon_{xx}, \epsilon_{yy}, \epsilon_{zz}, \epsilon_{yz}, \epsilon_{xy}, \epsilon_{zx}) = 1
\end{equation}


\begin{align}\label{eq:14}
 I(\omega_t, \omega_\tau)
& \propto \left \langle \frac{f(\bar{\epsilon})}{p(\bar{\epsilon})} \right \rangle_p \int_{\bar{\epsilon_a}}^{\bar{\epsilon_b}}p(\bar{\epsilon}) \, d\bar{\epsilon} \\
& \tilde{\propto} \frac{1}{N} \sum_i^N \frac{f(\bar{\epsilon}_i)}{p(\bar{\epsilon}_i)} \\
& \tilde{\propto} \frac{1}{N} \sum_i^N \rho (\omega_t, \omega_{\tau}, \epsilon_{xx_i}, \epsilon_{yy_i}, \epsilon_{zz_i}, \epsilon_{yz_i}, \epsilon_{xy_i}, \epsilon_{zx_i}) \\
\end{align}

In [32]:
import numpy as np
A = np.arange(1, 10).reshape(3, 3)
B = np.arange(1, 4)

In [33]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
B

array([1, 2, 3])

In [35]:
np.sum([A, B], axis = 0)

ValueError: could not broadcast input array from shape (3,3) into shape (3,)

In [8]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])